# Default values for redhat-sp-otel-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mode: "deployment"


image:
  repository: quay.io/raks.tt/otel-collector-contrib
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  args: "--config=/etc/otel/collector/config.yaml"


# OpenTelemetry Collector executable
command:
  name: otelcol-contrib
  extraArgs: []


extraEnvs:
  - name: HONEYCOMB_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: "otel_collector_name-opentelemetry-collector"
        key: honeycomb_token
  - name: HONEYCOMB_API_DEV_TOKEN
    valueFrom:
      secretKeyRef:
        name: "otel_collector_name-opentelemetry-collector"
        key: honeycomb_dev_token
  - name: HONEYCOMB_API_STAGE_TOKEN
    valueFrom:
      secretKeyRef:
        name: "otel_collector_name-opentelemetry-collector"
        key: honeycomb_stage_token
  - name: SIGNALFX_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: "otel_collector_name-opentelemetry-collector"
        key: splunk_observability_access_token
extraVolumes:
  - name: "otel_collector_redhat_ca_bundle"
    configMap:
      name: "otel_collector_redhat_ca_bundle"
      defaultMode: 420

extraVolumeMounts:
  - name: "otel_collector_redhat_ca_bundle"
    mountPath: /etc/ssl/certs/ca-certificates.crt
    subPath: ca-bundle.crt


# Resource limits & requests. Update according to your
# own use case as these
# values might be too low for a typical deployment.
resources:
  limits:
    cpu: 1000m
    memory: 2000mi
  requests:
    cpu: 1000m
    memory: 2000mi


# only used with deployment mode
replicaCount: 2

application:
  label: "sp-otel-collector"

service:
  #  type: LoadBalancer for mpp environment only
  type: ClusterIP
  annotations: {}
  # Configuration for ports
  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
      name: otlp-grpc
    otlphttp:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP
      name: otlp-http
    otlpdev:
      enabled: true
      containerPort: 4319
      servicePort: 4319
      hostPort: 4319
      protocol: TCP
      name: otlp-grpc-dev
    otlpdevhttp:
      enabled: true
      containerPort: 4320
      servicePort: 4320
      hostPort: 4320
      protocol: TCP
      name: otlp-http-dev
    otlpstage:
      enabled: true
      containerPort: 4321
      servicePort: 4321
      hostPort: 4321
      protocol: TCP
      name: otlp-grpc-stage
    otlpstagehttp:
      enabled: true
      containerPort: 4322
      servicePort: 4322
      hostPort: 4322
      protocol: TCP
      name: otlp-http-stage
    jaegercompact:
      enabled: false
    jaegerthrift:
      enabled: false
    jaegergrpc:
      enabled: false
    zipkin:
      enabled: false
  ingress:
    enabled: false

tokens:
  honeycomb_dev_token: ""
  honeycomb_stage_token: ""
  honeycomb_prod_token: ""
  signalfx_default: ""
  ssh_private_key: ""

# autoscaling is used only if deployment enabled
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
