apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.label }}-deployment
  labels:
    app: {{ .Values.application.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.label }}
    spec:
      containers:
        - name: {{ .Values.application.label }}
          image: {{ .Values.image.repository }}
          args:
            - {{ .Values.image.args | quote }}
          ports:
            {{- range $otlp := .Values.service.ports }}
           - name:  {{ $otlp.name }}
             containerPort:  {{ $otlp.containerPort | int }}
            {{- end }}
          env:
           {{- range $env := .Values.extraEnvs }}
           - name: {{ $env.name  }}
             valueFrom:
               secretKeyRef:
                 name: {{ $.Values.application.label }}-env
                 key: {{ $env.valueFrom.secretKeyRef.key }}
           {{- end }}
          volumeMounts:
            - name: {{ .Values.application.label }}-config
              mountPath: /etc/otel/collector/config.yaml
              subPath: config.yaml
            - name: {{ .Values.application.label }}-ca-bundle
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-bundle.crt
      volumes:
        - name: {{ .Values.application.label }}-config
          configMap:
            name: {{ .Values.application.label }}-config
        - name: {{ .Values.application.label }}-ca-bundle"
          configMap:
            name: {{ .Values.application.label }}-ca-bundle"
            defaultMode: 420
