apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Values.application.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.label }}
    spec:
      containers:
        - name: {{ .Values.application.label }}
          image: {{ .Values.image.repository }}
          args:
            - {{ .Values.image.args | quote }}
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: {{ .Chart.Name }}-config
              mountPath: /etc/otel/collector/config.yaml
              subPath: config.yaml
      volumes:
        - name: {{ .Chart.Name }}-config
          configMap:
            name: {{ .Chart.Name }}-config
