apiVersion: v1
data:
  # we should do it with iteration through value secrets
  honeycomb_dev_token: {{ .Values.tokens.honeycomb_dev_token }}
  honeycomb_stage_token: {{ .Values.tokens.honeycomb_stage_token }}
  honeycomb_token: {{ .Values.tokens.honeycomb_prod_token }}
  signalfx_default: {{ .Values.tokens.signalfx_default }}
  ssh_private_key: {{ .Values.tokens.ssh_private_key }}
kind: Secret
metadata:
  labels:
    app: {{ .Values.application.label }}
  name: {{ .Chart.Name }}-secret