apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.label }}-service
  labels:
    app: {{ .Values.application.label }}
spec:
  selector:
    app: {{ .Values.application.label }}
  ports:
    {{- range $otlp := .Values.service.ports }}
   - name: {{ $otlp.name  }}
     protocol: {{ $otlp.protocol }}
     port: {{ $otlp.servicePort | int }}
     targetPort: {{ $otlp.hostPort | int }}
    {{- end }}